services:
  api:
    image: node:20
    working_dir: /app
    volumes:
      - ./api:/app
      - /app/node_modules # コンテナ内node_modulesをホストのファイルシステムから分離
    ports:
      - "3000:3000"
      - "9229:9229"  # デバッグポート
    command: /bin/sh -c "npm i && npm run dev"
    depends_on:
      db:
        condition: service_healthy # db の起動が完了するまで待つ

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_volume:/var/lib/postgresql/data # データを永続化

volumes:
  db_volume:
